### ISSUE TITLE
Donor search process

### ISSUE THREAD

**Issue by KhirulIslam** [CraftsmenLtd/BloodConnect#156]
We need to find donors with the following parameters. 

1. Filter by the last donation date. (User specified)
2. location filter. (User specified)
3. Blood group filter. (User specified)
4. Filter by vaccination. (Backend)
5. Opt-out fitter for travel or any other unspecified reason. (Backend)
6. Include blood bank and organization in search results. (Backend and option in app end to skip)
7. Skip incomplete doners. (Backend)

Backend marked parameters should be handled behind the scenes for app users and User specified will be included input for org-users. Check [here](https://drive.google.com/file/d/1ya9swGl5iBPYcSVBcL0NmUqBUIE5DHvI/view?usp=sharing) for detailed design

**Proposed Solution:**
This will be part of the donor search and notification step specified in the detailed design. This also includes tuning geohash length and retry dynamodb search with tuned geohash length. As we are searching donor details it can easily exceeds step function's data limit, we can use step function's distributed map to tackle the issue

##Task breakdown : 

- [ ] prepare dynamodb search parameter in query generation step with retry logic the adjust with dynamodb RCU. Query generation step must include selective fields that we need for notification.
- [ ] Dynamodb integration and store results in s3 for later usage

## Acceptance Criteria
- [ ] Elegable donors are found from the dynamodb and stored in s3 for later process

## Documentation References
- Check [here](https://drive.google.com/file/d/1ya9swGl5iBPYcSVBcL0NmUqBUIE5DHvI/view?usp=sharing) for detailed design

**Comment by mahinuzzaman** [comment]
story points 3

**Comment by EbrahimAli-RU** [comment]
Story point 3

**Comment by Shahed-Chy-Suzan** [comment]
story points 4
