### ISSUE TITLE
Fix Authentication Error in APK Built

### ISSUE THREAD

**Issue by mahinuzzaman** [CraftsmenLtd/BloodConnect#251]
If we build the app's APK in preview mode, it encounters an error during the authentication process

**Tasks**:  
- [ ] Investigate the root cause of the authentication error.  
- [ ] Test authentication in dev, preview, and production builds.  
- [ ] Implement fixes to ensure authentication works in all modes. 

**Acceptance Criteria**:  
- [ ] The app successfully completes authentication when built in preview and production mode without any errors.
- [ ] Thorough testing for email and SSO login
