### ISSUE TITLE
Add Phone Number Input for SSO Login

### ISSUE THREAD

**Issue by mahinuzzaman** [CraftsmenLtd/BloodConnect#254]
The phone number input field is missing during SSO login. Add a phone number input to the SSO login flow to ensure required information is collected.

**Tasks**:  
- [ ] Add a phone number input field to the SSO login form

**Acceptance Criteria**:  
- [ ] A phone number input field is displayed on the update profile after SSO login. 
- [ ] Phone number added in the database
