### ISSUE TITLE
Analyze and Optimize Production Build Size

### ISSUE THREAD

**Issue by mahinuzzaman** [CraftsmenLtd/BloodConnect#264]
Review the production build size to identify opportunities for optimization. Implement strategies like code minification and component atomization to reduce size and improve performance

**Tasks**:  
- [ ] Check the production build size, gather details, and Identify large dependencies or components contributing to the build size.  
- [ ] Enable code minification and other modifications in the code and build process to reduce size

**Acceptance Criteria**:  
- [ ] A detailed analysis of the production build size
- [ ] Build size is reduced without breaking functionality.  
- [ ] Large components are atomized where applicable, improving reusability.

**Comment by Rezwanul-Haque** [comment]
I was looking into this and found that the production build size `34.7MB` which was already minified. We can further investigate after the first release to reduce the size.

@Biplob14 Bhai

**Comment by Biplob14** [comment]
@shuaibq3 vai, should we keep the ticket for now in our backlog so that we can add our future improvement or any other optimization is necessary for our first release?

**Comment by Rezwanul-Haque** [comment]
App size in google play  ~14Mb.
